#index:
#    path: /
#    controller: App\Controller\DefaultController::index
generate_pdf:
    path: '/generate-pdf/{id}'
    controller: App\Controller\CommandeController::generatePdf
    methods: ['GET']